ASPMVCProjektSklep/Controllers/AdressController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ASPMVCProjektSklep.Models;
using Microsoft.AspNet.Identity;

namespace ASPMVCProjektSklep.Controllers
{
    public class AdressController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Adresses
        public ActionResult Index()
        {
            return View(db.Adresses.ToList());
        }

        // GET: Adresses/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Adress adress = db.Adresses.Find(id);
            if (adress == null)
            {
                return HttpNotFound();
            }
            return View(adress);
        }

        // GET: Adresses/Create
        [Authorize]
        public ActionResult Create()
        {
            return View();
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,city,street,building,apartment,postalCode")] Adress adress)
        {

            var userId = User.Identity.GetUserId();
            ApplicationUser appUser = db.Users.FirstOrDefault(x => x.Id == userId);
            adress.User = appUser;

            if (ModelState.IsValid)
            {
                db.Adresses.Add(adress);
                db.SaveChanges();
                return RedirectToAction("Index", "Manage");
            }

            return View(adress);
        }

        // GET: Adresses/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Adress adress = db.Adresses.Find(id);
            if (adress == null)
            {
                return HttpNotFound();
            }
            return View(adress);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,city,street,building,apartment,postalCode")] Adress adress)
        {
            if (ModelState.IsValid)
            {
                db.Entry(adress).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(adress);
        }

        [Authorize]
        public ActionResult Delete(int? id)
        {
            Adress adress = db.Adresses.Find(id);

            if (adress.Orders.Count > 0)
            {
                return RedirectToAction("Index", "Manage");
            }

            db.Adresses.Remove(adress);
            db.SaveChanges();
            return RedirectToAction("Index", "Manage");
        }

        [Authorize]
        public PartialViewResult ShowAdresses()
        {
            ICollection<Adress> adresses = new List<Adress>();

            var userId = User.Identity.GetUserId();

            adresses = db.Adresses.Where(b => b.User.Id == userId).ToList();

            return PartialView("~/Views/Adress/ShowAdresses.cshtml", adresses);
       
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ASPMVCProjektSklep/Views/Adress/Create.cshtml
@model ASPMVCProjektSklep.Models.Adress

@{
    ViewBag.Title = "Create";
}

<h2>Dodaj adres</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Adress</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.city, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.city, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.city, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.street, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.street, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.street, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.building, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.building, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.building, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.apartment, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.apartment, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.apartment, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.postalCode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.postalCode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.postalCode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Dodaj" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Powrót", "Index", "Manage")
</div>

ASPMVCProjektSklep/Views/Adress/Delete.cshtml
@model ASPMVCProjektSklep.Models.Adress

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Adress</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.city)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.city)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.street)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.street)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.building)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.building)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.apartment)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.apartment)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.postalCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.postalCode)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ASPMVCProjektSklep/Views/Adress/Details.cshtml
@model ASPMVCProjektSklep.Models.Adress

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Adress</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.city)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.city)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.street)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.street)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.building)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.building)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.apartment)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.apartment)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.postalCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.postalCode)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ASPMVCProjektSklep/Views/Adress/Edit.cshtml
@model ASPMVCProjektSklep.Models.Adress

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Adress</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.city, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.city, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.city, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.street, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.street, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.street, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.building, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.building, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.building, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.apartment, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.apartment, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.apartment, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.postalCode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.postalCode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.postalCode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ASPMVCProjektSklep/Views/Adress/Index.cshtml
@model IEnumerable<ASPMVCProjektSklep.Models.Adress>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.city)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.street)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.building)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.apartment)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.postalCode)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.city)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.street)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.building)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.apartment)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.postalCode)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

ASPMVCProjektSklep/Views/Adress/ShowAdresses.cshtml
@model IEnumerable<ASPMVCProjektSklep.Models.Adress>

@{
    ViewBag.Title = "ShowAdresses";


}

<h2>Twoje adresy</h2>

@foreach (var adress in Model)
{
    <div class="panel panel-default">
        <div class="panel-body">
            <p>Miasto: @adress.city</p>
            <p>Ulica: @adress.street</p>
            @if (adress.apartment.Length > 0)
            {
                <p>
                    Budynek:
                    @adress.building / @adress.apartment
                </p>

            }
            else
            {
                <p>
                    Budynek:
                    @adress.building
                </p>
            }
            <p>Kod pocztowy: @adress.postalCode</p>

            <div class="row">
                <div class="col-md-6"></div>
                <div class="col-md-3"></div>
                <div class="col-md-3">    <a href="@Url.Action("Delete","Adress", new { id = @adress.Id })" class="btn btn-danger pull-right" role="button">Usuń adres</a></div>
            </div>


        </div>
    </div>
}